name: 每日情话邮件

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 执行发邮件
        env:
          TZ: Asia/Shanghai
          FROM_ADDR: ${{ secrets.FROM_ADDR }}
          AUTH_CODE: ${{ secrets.AUTH_CODE }}
          TO_ADDR: ${{ secrets.TO_ADDR }}
        run: python send_email.py
